### ISSUE TITLE
Your demo.js file is missing from the repository

### ISSUE THREAD

**Issue by learntoswim** [gocanto/google-autocomplete#17]
Looking for examples, yet the file has since been removed.

**Comment by gocanto** [comment]
https://github.com/gocanto/google-autocomplete/blob/master/src/js/index.js

**Comment by learntoswim** [comment]
Thanks, there is a mistake in your `README.md` which points to an old `demo.js`

Great plugin. 👍

**Comment by gocanto** [comment]
Fixed on https://github.com/gocanto/google-autocomplete/pull/18

thanks buddy.
