### ISSUE TITLE
street_number is missing

### ISSUE THREAD

**Issue by cdubant** [gocanto/google-autocomplete#22]
Hi Gocanto

Thanks for your great google autocomplete which is extremely easy to implement.

I noticed that there was one thing missing though (street_number) which is returned by the API.

I could implement it easily on my project but for the benefits of others I think this would be a great improvement for your vue wrapper.

Have a great day and thanks again !

**Comment by cdubant** [comment]
The only change needed is to add : 

`street_number: 'short_name',`

in the inputs section in components\googleAutocomplete.vue

**Comment by gocanto** [comment]
Hey, thanks for suggesting this out. I will be adding this this week. 

Thanks for testing

**Comment by gocanto** [comment]
Fixed on

https://github.com/gocanto/google-autocomplete/blob/master/src/js/bootstrap.js#L32
