### ISSUE TITLE
./../Libraries/Autocomplete not found

### ISSUE THREAD

**Issue by monmon-dotdev** [gocanto/google-autocomplete#25]
Hi Thank you for the great work!!
I just installed the latest version with npm, but the following error occurred:

Module not found: Error: Can't resolve './../Libraries/Autocomplete' in '/path/node_modules/google-autocomplete-
vue/dist/Components'

I guess there is no Libraries/* in the compiled package? :)
Thank you!

**Comment by gocanto** [comment]
working on it

**Comment by gocanto** [comment]
just published patch, but I am testing everything before closing this issue. Thanks for testing!

**Comment by gocanto** [comment]
@monmon-dotdev Hey, did you test it again? 

I just did the final test in a personal project and seems to be working. Let me know if you have any other issues. 

As always, thank you for testing.

**Comment by monmon-dotdev** [comment]
Hi @gocanto just tested it, all good! Thank you so much :)
