### ISSUE TITLE
trying to use this autocomplete on same page as a maps

### ISSUE THREAD

**Issue by vesper8** [gocanto/google-autocomplete#35]
I know this may be outside of the scope of this project but I would really appreciate any insight

I've got this autocomplete working perfectly but I'm trying to use it on the same page as a map that's using this

https://www.npmjs.com/package/vue2-google-maps

Got the map working on its own as well but if I try to use both I get the dreaded 

"You have included the Google Maps API multiple times" error

I could perhaps get around this by using the map inside an iframe, but then my other problem is that while the map initializes the api inside a .vue component, this plugin requires that the initialization be in the bootstrap.js, so even if I'm on a page that only uses one of the two plugins, it still initializes twice and throws the error.

How can I have it so that it only initializes the api on pages where the component is actually used?

Even better though would be for a solution for using both on the same page

Thanks!!

**Comment by gocanto** [comment]
The issue here is I include google map API when loading, so I guess that library too. I had researched once for getting a better loader for google API, but I was not able yet. If you have any idea how this could be accomplished, I would like to hear more about it.

**Comment by vesper8** [comment]
Not sure.. I battled this issue for over an hour and then realized that the other package has its own gmap-autocomplete which pretty much does the same as yours, so I just used that and it works great.

Googling about this problem though certainly brought out a lot of threads about people having difficulty with it. When you used to do things manually using jquery you could simply change the callback to your own initialize function and in there you could init multiple things (places autocomplete, map, etc). But now that it's all hidden under vue components and compiled too.. it's much harder and scary to go in and change the callback

**Comment by gocanto** [comment]
I defenetly will give it a try 😃
