### ISSUE TITLE
Error when running Laravel Mix with production flag

### ISSUE THREAD

**Issue by redenz** [gocanto/google-autocomplete#44]
First of all I like the simplicity of this package.  I know you are using larave-elixir but wanted to see if you know what would be causing this issue with Laravel Mix.  When I compile using the production flag  
`
npm run production
`
I get the following error 
`
/js/app.js from UglifyJs
SyntaxError: Unexpected token: name (Autocomplete) [./~/google-autocomplete-vue/dist/Libraries/Autocomplete.js:11,0][/js/app.js:26241,6]
`

**Comment by gocanto** [comment]
what are you using for the compilation?

**Comment by redenz** [comment]
I'm using a default webpack.mix.js from Laravel mix meaning I have not added any plugins.  All my vue components are compiled with 

mix.js('resources/assets/js/app.js', 'public/js')

**Comment by gocanto** [comment]
Well, Let me look into it. I have not used mix myself yet.

**Comment by redenz** [comment]
Sounds good. Thanks. If there's any other info you need from me please let me know
