### ISSUE TITLE
Auto complete z-index is lower than vue strap modal

### ISSUE THREAD

**Issue by AsrorWali** [gocanto/google-autocomplete#5]
Hey,

Thanks for the component. But the results are under my modal and I cant seem to find a easy way to fix this. Especially since the auto complete does something in the head and I dont understand what it does.

Could you help me out here please ?

Greetings,

**Comment by gocanto** [comment]
Sure, just share either a link or pic to see its behavior.

**Comment by AsrorWali** [comment]
Yo,

https://gyazo.com/ea7b1e2a986459cc9f50fd3c5c3ab443
Hope this picture helps

Greetings,

**Comment by gocanto** [comment]
well, it seems to be a styling issue. Check the component z-index and bring it to the front. I think that should be it. Otherwise, I misunderstood the problem, so I would need a better picture tho.

**Comment by AsrorWali** [comment]
On what tag/class do i change the z-index ? I tried to do it on the input but that doesnt work.
And because i have no idea how the list get rendered I dont know which class to override in my css

**Comment by gocanto** [comment]
The list gets rendered on ```google server```, so you will have to find out its ```style classe``` and overwrite them within your css file.
