### ISSUE TITLE
"class" is a reserved attribute error

### ISSUE THREAD

**Issue by vcayetano** [gocanto/google-autocomplete#58]
[Vue warn]: "class" is a reserved attribute and cannot be used as component prop.

found in

---> <GoogleAutocomplete> at node_modules/google-autocomplete-vue/dist/Components/googleAutocomplete.vue

![image](https://user-images.githubusercontent.com/58948817/74367265-2d156a00-4d97-11ea-862d-9041143e79fe.png)

**Comment by gocanto** [comment]
thanks for spotting this. 

would you like to send a PR?

**Comment by BaiMaoLi** [comment]
I think, this is issue.
Of course it is working without fixing.
But class is reserved attribute of html, so you have to avoid to use the reserved word "class"
