### ISSUE TITLE
Some code is not good in demo file

### ISSUE THREAD

**Issue by BaiMaoLi** [gocanto/google-autocomplete#60]
This is wrong.

```
 if (Object.keys(paypload.place).length > 0) {
                this.address = payload.address;
                this.response = payload.response;
}

```

**Comment by gocanto** [comment]
Would you send a PR? 🙂

**Comment by BaiMaoLi** [comment]
![image](https://user-images.githubusercontent.com/39260816/83017874-fd912180-a056-11ea-914c-fc9a9f4da442.png)

**Comment by BaiMaoLi** [comment]
PR means print screen? or Project?

**Comment by gocanto** [comment]
I meant you fixing the issue and sending the changes through github for everybody to have 🙂

**Comment by BaiMaoLi** [comment]
Oh, I see sir.
But I have never experienced in contributing other's repository.

**Comment by gocanto** [comment]
Ok, I will take a look at it later this week :)
